### ISSUE TITLE
NACA airfoils generator

### ISSUE THREAD

**Issue by jorgepiloto** [AeroPython/scikit-aero#26]
It would be tremendously useful to add some NACA generators that can return the user not only the points that define the airfoils, but also plot them in an easy way.

The idea is to implement them as constructors for class called `NACA`, having something similar to:

```python
from skaero.geometry.naca import NACA
naca0012 = NACA.4series(name='0012', chord='1', N=100)
```

At least, 4 and 5 series should be easy to implement:

* [ ] 4-Series
* [ ] 5-Series

More information about these profiles can be found at: https://en.wikipedia.org/wiki/NACA_airfoil

**Comment by Juanlu001** [comment]
Maybe it's already available? https://github.com/mathLab/BladeX

**Comment by jorgepiloto** [comment]
Wow! I am start thinking there exists a package for anything in Python :rofl:

**Comment by jorgepiloto** [comment]
Closing this. There are really good Python implementations as Juanlu suggested and an amazing new package related to numerical potential flow computations: [AeroSandbox](https://github.com/peterdsharpe/AeroSandbox)
